### ISSUE TITLE
Python/Robot version info

### ISSUE THREAD

**Issue by GagnonNicolas** [MichaelHallik/robot-framework-remote-swing-demo-project#1]
Hi.

With which version of Robot and Python did you test your example?

I am running:  RF 3.1.2  on Python 3.8 with RemoteSwingLibrary 2.2.4 and I am getting  a null pointer error right upfront trying to select the main window. 

(Info: going back to jython and Python 2.X is not an option as I have lot's of 3.x code in other libraries.) 
Thanks.

**Comment by MichaelHallik** [comment]
Hi,

I had tested with Python 2.7.x.

And further:

Robot Framework 2.8.3
Java JRE/JDK (1.6 or later).
Windows (7, 8, 10)

Regards,
Michael

**Comment by MichaelHallik** [comment]
Closing, because no further response came.
